### ISSUE TITLE
Regarding cocoapods 

### ISSUE THREAD

**Issue by SURENDRA7700** [VoIPGRID/VialerSIPLib-iOS#3]
while doing this keys.h also not visible it is missing and pods also not working ..i hope reslove this fast .i want to use this library thank you

**Comment by Joker666** [comment]
Duplicate of #1 

As I mentioned keys.sample.h is there and you can already start using the library by drag and drop to your project

**Comment by m-vellinga** [comment]
I'm going to close this issue as duplicate. As Joker666 stated there is a Keys.sample.h file available to use. The README.md also clarified the use of the Keys.sample.h

**Comment by SURENDRA7700** [comment]
here keys.sample .h not there in cloned project .can you please tag me compiled code successfully 
.now aliso aim working on it
