### ISSUE TITLE
framework error

### ISSUE THREAD

**Issue by SURENDRA7700** [VoIPGRID/VialerSIPLib-iOS#4]
![screen shot 2016-07-29 at 3 21 59 pm](https://cloud.githubusercontent.com/assets/13854872/17244586/48b2fd2e-55a0-11e6-9f04-a53a6a2d988c.png)

Library is very good just .......framework dependanceis  error  can you please solve . i have so much hope for this libaray .

**Comment by mohpor** [comment]
I'm getting this error too.
After a `pod update` or `pod install` on the example project, it seems like the static framework that is being added to the pod dependencies i.e. `VialerPJSIP.framework` doesn't contain the required header files. You can verify that by opening the `.framework` file and check there is no header files nor compiled data.
I'm trying to build the framework and add it to the example project manually. Will update upon results.

**Comment by r3b3l** [comment]
@SURENDRA7700 @mohpor 
We are investigating the problem, somehow Cocoapods does not fetch all files specified in de podspec.

 As a work around I can offer to add the following line to the Podfile in the example directory:

`pod 'Vialer-pjsip-iOS', :git => 'https://github.com/VoIPGRID/Vialer-pjsip-iOS'`

add it directly under `def pods_for_all_targets`

**Comment by r3b3l** [comment]
the /Example/Pods directory was .gitignored-ed but not removed from version control. Thus a pod install/update did not fetch the 'Vialer-pjsip-iOS' pod from git but instead used an older incomplete version of the pod found from /Example/Pods.

This has been fixed.

**Comment by SURENDRA7700** [comment]
soory, i did not understabd please msg me how to run with out isuues .i am facing problem

**Comment by bkr1989** [comment]
@redmerloen  @bobvoorneveld  Hi bob&redmerloen i have my own modified PJSIP library.. can i integrate it into vailer....if so how....please help me out in this... i know you are not in this project now.. bt ur answer may help me....my team added encryption functionality in PJSIp lib..

**Comment by rahuld600** [comment]
It's still not working
